name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          cd real-time-story-generation-llm
          pip install -r requirements.txt
          pip install -e .
      - name: Check code formatting
        run: black --check real-time-story-generation-llm
      - name: Run tests
        run: |
          cd real-time-story-generation-llm
          PYTHONPATH=src pytest -q tests
      - name: Build Docker image
        run: docker build -t story-rt:latest ./real-time-story-generation-llm
